client_config_backend: file
client_config:
    client_id: 1003626969286-fqed7gokp7ss119ovq178kppslj4aimc.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive